--- #YAML:1.0
name: logic-kleene
version: 0.03
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: Kleene three-valued logic
license: perl
requires:
  overload: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  logic::kleene:
    file: lib/logic/kleene.pm
    version: 0.03
generated_by: Module::Build version 0.2611
